name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies with legacy-peer-deps
      run: npm install --legacy-peer-deps

    - name: Run lint
      run: npm run lint || true  

    - name: Run tests
      run: npm test -- --watchAll=false || true  
